[View in Colaboratory](https://colab.research.google.com/github/sungreong/TIL/blob/master/missing_value_,_categorical_variable_,_scaling.ipynb)

## missing value ( drop , inplace)

In [1]:
## 결측치
## 라벨링된 데이터 (카테고리) 
## 스케일이 너무 차이가 클 때 

import pandas as pd
import numpy as np

raw_data = {'first_name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'],
        'last_name': ['Miller', np.nan, 'Ali', 'Milner', 'Cooze'],
        'age': [42, np.nan, 36, 24, 73],
        'sex': ['m', np.nan, 'f', 'm', 'f'],
        'preTestScore': [4, np.nan, np.nan, 2, 3],
        'postTestScore': [25, np.nan, np.nan, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])
df

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [3]:
## 얼마나 비는지 계산
df.isnull().sum()  / len(df)

first_name       0.2
last_name        0.2
age              0.2
sex              0.2
preTestScore     0.4
postTestScore    0.4
dtype: float64

In [5]:
##
df_no_missing = df.dropna()
df_no_missing

first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [9]:
df_cleaned = df.dropna(how="all")
df_cleaned

first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
2       Tina       Ali  36.0   f           NaN            NaN
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [11]:
df["location"] = np.nan
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           NaN            NaN       NaN
2       Tina       Ali  36.0    f           NaN            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [12]:
df.dropna(axis =1 , how="all")

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [29]:
df.dropna(axis=0 , thresh = 3 )

## thresh  / threshold  3개 이상 없으면 drop 해라 

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       NaN
2       Tina       Ali  36.0   f           3.0           70.0       NaN
3       Jake    Milner  24.0   m           2.0           62.0       NaN
4        Amy     Cooze  73.0   f           3.0           70.0       NaN

In [14]:
df.fillna(0)

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       0.0
1          0         0   0.0   0           0.0            0.0       0.0
2       Tina       Ali  36.0   f           0.0            0.0       0.0
3       Jake    Milner  24.0   m           2.0           62.0       0.0
4        Amy     Cooze  73.0   f           3.0           70.0       0.0

In [17]:
print(df["preTestScore"].median())
print(df["preTestScore"].mode())
df["preTestScore"].mean()


3.0
0    2.0
1    3.0
2    4.0
dtype: float64


3.0

In [0]:
df["preTestScore"].fillna(df["preTestScore"].mean() , inplace=True)

In [20]:
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           3.0            NaN       NaN
2       Tina       Ali  36.0    f           3.0            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [22]:
df.groupby("sex")["postTestScore"].transform("mean")

0    43.5
1     NaN
2    70.0
3    43.5
4    70.0
Name: postTestScore, dtype: float64

In [26]:
df["postTestScore"].fillna(
    df.groupby("sex")["postTestScore"].transform("mean"), inplace=True)
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           3.0            NaN       NaN
2       Tina       Ali  36.0    f           3.0           70.0       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [28]:
df[df["age"].notnull() & df["sex"].notnull() ]

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       NaN
2       Tina       Ali  36.0   f           3.0           70.0       NaN
3       Jake    Milner  24.0   m           2.0           62.0       NaN
4        Amy     Cooze  73.0   f           3.0           70.0       NaN

## category data

In [30]:
## one-hot encoding
edges = pd.DataFrame({'source': [0, 1, 2],
                   'target': [2, 2, 3],
                       'weight': [3, 4, 5],
                       'color': ['red', 'blue', 'blue']})

edges

color  source  target  weight
0   red       0       2       3
1  blue       1       2       4
2  blue       2       3       5

In [31]:
edges.dtypes

color     object
source     int64
target     int64
weight     int64
dtype: object

In [32]:
edges["color"]

0     red
1    blue
2    blue
Name: color, dtype: object

In [33]:
pd.get_dummies(edges)

source  target  weight  color_blue  color_red
0       0       2       3           0          1
1       1       2       4           1          0
2       2       3       5           1          0

In [34]:
pd.get_dummies(edges["color"])

blue  red
0     0    1
1     1    0
2     1    0

In [36]:
print(edges[["color"]])
pd.get_dummies(edges[["color"]])

  color
0   red
1  blue
2  blue


color_blue  color_red
0           0          1
1           1          0
2           1          0

In [37]:
weight_dict = {3:"M", 4:"L", 5:"XL"}
edges["weight_sign"] = edges["weight"].map(weight_dict)
edges

color  source  target  weight weight_sign
0   red       0       2       3           M
1  blue       1       2       4           L
2  blue       2       3       5          XL

In [38]:
weight_sign = pd.get_dummies(edges["weight_sign"])
weight_sign

L  M  XL
0  0  1   0
1  1  0   0
2  0  0   1

In [39]:
pd.concat([edges , weight_sign] , axis= 1 )

color  source  target  weight weight_sign  L  M  XL
0   red       0       2       3           M  0  1   0
1  blue       1       2       4           L  1  0   0
2  blue       2       3       5          XL  0  0   1

In [41]:
print(edges)
pd.get_dummies(edges).values

  color  source  target  weight weight_sign
0   red       0       2       3           M
1  blue       1       2       4           L
2  blue       2       3       5          XL


array([[0, 2, 3, 0, 1, 0, 1, 0],
       [1, 2, 4, 1, 0, 1, 0, 0],
       [2, 3, 5, 1, 0, 0, 0, 1]])

In [42]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])
df

regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [43]:
bins =[0, 25, 50, 75 , 100]
group_names = ['Low', 'Okay', 'Good', 'Great']
categories = pd.cut(df["postTestScore"] , bins , labels=group_names)
categories

0       Low
1     Great
2      Good
3      Good
4      Good
5       Low
6     Great
7      Good
8      Good
9      Good
10     Good
11     Good
Name: postTestScore, dtype: category
Categories (4, object): [Low < Okay < Good < Great]

In [44]:
df["categories"] = pd.cut(df["postTestScore"] , bins , labels=group_names)
pd.value_counts(df["categories"])

Good     8
Great    2
Low      2
Okay     0
Name: categories, dtype: int64

In [45]:
pd.get_dummies(df)

preTestScore  postTestScore  regiment_Dragoons  regiment_Nighthawks  \
0              4             25                  0                    1   
1             24             94                  0                    1   
2             31             57                  0                    1   
3              2             62                  0                    1   
4              3             70                  1                    0   
5              4             25                  1                    0   
6             24             94                  1                    0   
7             31             57                  1                    0   
8              2             62                  0                    0   
9              3             70                  0                    0   
10             2             62                  0                    0   
11             3             70                  0                    0   

    regiment_Scouts  company_1st  company_2nd  name_Ali  name_Cooze  \
0                 0            1            0         0           0   
1                 0            1            0         0           0   
2                 0            0            1         1           0   
3                 0            0            1         0           0   
4                 0            1            0         0           1   
5                 0            1            0         0           0   
6                 0            0            1         0           0   
7                 0            0            1         0           0   
8                 1            1            0         0           0   
9                 1            1            0         0           0   
10                1            0            1         0           0   
11                1            0            1         1           0   

    name_Jacobson        ...         name_Milner  name_Piger  name_Riani  \
0               0        ...                   0           0           0   
1               1        ...                   0           0           0   
2               0        ...                   0           0           0   
3               0        ...                   1           0           0   
4               0        ...                   0           0           0   
5               0        ...                   0           0           0   
6               0        ...                   0           0           0   
7               0        ...                   0           0           0   
8               0        ...                   0           0           0   
9               0        ...                   0           1           0   
10              0        ...                   0           0           1   
11              0        ...                   0           0           0   

    name_Ryaner  name_Sloan  name_Sone  categories_Low  categories_Okay  \
0             0           0          0               1                0   
1             0           0          0               0                0   
2             0           0          0               0                0   
3             0           0          0               0                0   
4             0           0          0               0                0   
5             0           0          0               1                0   
6             1           0          0               0                0   
7             0           0          1               0                0   
8             0           1          0               0                0   
9             0           0          0               0                0   
10            0           0          0               0                0   
11            0           0          0               0                0   

    categories_Good  categories_Great  
0                 0                 0  
1                 0                 1  
2                 1

## using scikit-learn preprocessing



In [0]:
raw_example = df.as_matrix()
raw_example[:3]
data = raw_example.copy()

In [0]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [49]:
raw_example[:, 0 ]1

array(['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons',
       'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts',
       'Scouts'], dtype=object)

In [50]:
le.fit(raw_example[:, 0])

LabelEncoder()

In [51]:
le.classes_  ## 0 1 2 로 기준을 정한다 

array(['Dragoons', 'Nighthawks', 'Scouts'], dtype=object)

In [52]:
le.transform( raw_example[:, 0])  ## 실제 적용 

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [0]:
label_column = [0,1,2,5]
label_encoder_list =[]

for column_index in label_column :
    le = preprocessing.LabelEncoder()  ## encoder 생성
    le.fit(raw_example[:, column_index])  ## data 에 맞게 encoding fitting 기준을 세워주는 역할 
    data[: , column_index] = le.transform(raw_example[:, column_index ])  ## 실제데이터 -> labelling data
    label_encoder_list.append(le)
    del le
    

In [55]:
data[:3]

array([[1, 0, 4, 4, 25, 2],
       [1, 0, 2, 24, 94, 1],
       [1, 1, 0, 31, 57, 0]], dtype=object)

In [57]:
label_encoder_list[0].transform(raw_example[:10, 0 ])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2])

In [58]:
one_hot_enc = preprocessing.OneHotEncoder()
data[:,0].reshape(-1, 1 )

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [59]:
one_hot_enc.fit(data[:,0].reshape(-1, 1 ))

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [60]:
one_hot_enc.n_values_

array([3])

In [61]:
one_hot_enc.active_features_ ## 몇개의 변수가 있는지 

array([0, 1, 2])

In [63]:
onehotlabels = one_hot_enc.transform(data[:,0].reshape(-1, 1)).toarray()
onehotlabels

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

## feature_scaling 


* min-max normalization (0 ~ 1)
* z_score normalization 

* scaling 해도 분포는 변하지 않는다.
* 속도가 더 빨라지는 효과도 있다.

In [64]:
df = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],'B':[103.02,107.26,110.35,114.23,114.68], 'C':['big','small','big','small','small']})
df

A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

In [65]:
df["A"]

0    14.00
1    90.20
2    90.95
3    96.27
4    91.21
Name: A, dtype: float64

In [67]:
df["A"] - df["A"].min()

0     0.00
1    76.20
2    76.95
3    82.27
4    77.21
Name: A, dtype: float64

In [68]:
( df["A"] - df["A"].min() ) / ( df["A"].max() - df["A"].min() )

0    0.000000
1    0.926219
2    0.935335
3    1.000000
4    0.938495
Name: A, dtype: float64

In [69]:
df["A"] = ( df["A"] - df["A"].min() ) \
/ (df["A"].max() - df["A"].min() ) *(5-1)+1
df

A       B      C
0  1.000000  103.02    big
1  4.704874  107.26  small
2  4.741339  110.35    big
3  5.000000  114.23  small
4  4.753981  114.68  small

In [70]:
df["B"].mean() , df["B"].std()

(109.90799999999999, 4.901619120249964)

In [0]:
df["B"] = ( df["B"] - df["B"].mean()) \
/ (df["B"].std() )

In [72]:
df

A         B      C
0  1.000000 -1.405250    big
1  4.704874 -0.540230  small
2  4.741339  0.090174    big
3  5.000000  0.881749  small
4  4.753981  0.973556  small

In [0]:
def feture_scaling(df, scaling_strategy="min-max", column=None):
    if column == None:
        column = [column_name for column_name in df.columns]
    for column_name in column:
        if scaling_strategy == "min-max":
            df[column_name] = ( df[column_name] - df[column_name].min() ) /\
                            (df[column_name].max() - df[column_name].min()) 
        elif scaling_strategy == "z-score":
            df[column_name] = ( df[column_name] - \
                               df[column_name].mean() ) /\
                            (df[column_name].std() )
    return df

In [76]:
df = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],'B':[103.02,107.26,110.35,114.23,114.68], 'C':['big','small','big','small','small']})
df

A       B      C
0  14.00  103.02    big
1  90.20  107.26  small
2  90.95  110.35    big
3  96.27  114.23  small
4  91.21  114.68  small

In [77]:
feture_scaling(df,column=["A","B"])

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [78]:
import pandas as pd
import numpy as np

df = pd.io.parsers.read_csv(
    'https://raw.githubusercontent.com/rasbt/pattern_classification/master/data/wine_data.csv',
     header=None,
     usecols=[0,1,2]
    )

df.columns=['Class label', 'Alcohol', 'Malic acid']

df.head()

Class label  Alcohol  Malic acid
0            1    14.23        1.71
1            1    13.20        1.78
2            1    13.16        2.36
3            1    14.37        1.95
4            1    13.24        2.59

In [80]:
df = feture_scaling(df ,"min-max" , column=["Alcohol", "Malic acid"])
df.head()

Class label   Alcohol  Malic acid
0            1  0.842105    0.191700
1            1  0.571053    0.205534
2            1  0.560526    0.320158
3            1  0.878947    0.239130
4            1  0.581579    0.365613

In [82]:
from sklearn import preprocessing

df = pd.io.parsers.read_csv(
    'https://raw.githubusercontent.com/rasbt/pattern_classification/master/data/wine_data.csv',
     header=None,
     usecols=[0,1,2]
    )
df.columns=['Class label', 'Alcohol', 'Malic acid']
df.head()

Class label  Alcohol  Malic acid
0            1    14.23        1.71
1            1    13.20        1.78
2            1    13.16        2.36
3            1    14.37        1.95
4            1    13.24        2.59

In [0]:
from sklearn import preprocessing
std_scaler = preprocessing.StandardScaler().fit(df[['Alcohol', 'Malic acid']])

In [0]:
df_std = std_scaler.transform(df[["Alcohol", "Malic acid"]])

In [102]:
df_std.shape
df_std[1:5, :2]

array([[ 0.24628963, -0.49941338],
       [ 0.19687903,  0.02123125],
       [ 1.69154964, -0.34681064],
       [ 0.29570023,  0.22769377]])