In [1]:
import tensorflow as tf
from sklearn import datasets
import numpy as np

breast = datasets.load_breast_cancer()
x = breast["data"]

In [12]:
import os
path = './save_tf/basic_model.meta'
def load_model(file_path) :
    saver = tf.train.import_meta_graph(file_path)
    os.environ["CUDA_VISIBLE_DEVICES"]="-1"
    config=tf.ConfigProto(log_device_placement=True)
    config.gpu_options.allow_growth = True
    sess = tf.Session(config= config)
    saver.restore(sess, tf.train.latest_checkpoint('./save_tf/'))
    graph = tf.get_default_graph()
    ## INPUT 지정
    X = graph.get_tensor_by_name("input:0")
    ## OUTPUT 지정
    prob = graph.get_tensor_by_name("prob:0")
    return sess , X , prob

In [13]:
sess , X , prob = load_model( path)

In [14]:
probability = sess.run(prob , feed_dict={X : x[1:10,:]})
print(probability)

[[0.0000000e+00]
 [0.0000000e+00]
 [9.9492860e-01]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [6.2581897e-04]
 [4.7950314e-05]]


In [5]:
saver.restore(sess, tf.train.latest_checkpoint('./save_tf/'))
graph = tf.get_default_graph()

In [6]:
X = graph.get_tensor_by_name("input:0")
prob = graph.get_tensor_by_name("prob:0")

In [7]:
x[0:1,:]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

[0.]


In [9]:
probability = sess.run(prob , feed_dict={X : x})
print(probability)

[[0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [9.9492860e-01]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [6.2590837e-04]
 [4.7951937e-05]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [1.0000000e+00]
 [1.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [9.7610021e-01]
 [1.0000000e+00]
 [1.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [2.0861626e-07]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [9.9844599e-01]
 [1.0000000e+00]
 [1.0000000e+00]
 [8.9686513e-01]
 [2.3245811e-06]
 [9.9999994e-01]
 [0.0000000e+00]
 [0.0000000e+00]
 [4.2515755e-02]
 [0.0000000e+00]
 [1.0000000e+00]
 [5.6624413e-07]
 [9.9995232e-01]
 [9.9999964e-01]
 [1.0000000e+00]
 [1.0000000e+00]
 [1.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [1.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]
 [9.9999994e-0