In [6]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

sess = tf.InteractiveSession()
x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])


a=tf.cond(x>y, lambda: tf.add(x,y),lambda: tf.subtract(x,y))
sess.run([a,x,y])
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################


[0.74505556, 0.41584194, 0.32921362]

In [26]:
x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)


###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

x= tf.random_uniform([], -1, 1 ,dtype=tf.float32)
y= tf.random_uniform([], -1, 1 ,dtype=tf.float32)
def f1(x,y) :
    return x-y
def f2(x,y) :
  if x > y :
    return 0
out = tf.case({tf.less(x, y): lambda: tf.add(x, y), 
			tf.greater(x, y): lambda: tf.subtract(x, y)}, 
			default=lambda: tf.constant(0.0), exclusive=True)

###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

v1 =tf.constant([[0,-2,-1],[0,1,2]], name="const1")
print(v1.shape)
y=tf.zeros_like(v1)
out= tf.equal(v1,y, name="equal")

###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################
# YOUR CODE
a= [29.05088806,  27.61298943,  31.19073486,  29.35532951,
    30.97266006,  26.67541885,  38.08450317,  20.74983215,
    34.94445419,  34.45999146,  29.06485367,  36.01657104,
    27.88236427,  20.56035233,  30.20379066,  29.51215172,
    33.71149445,  28.59134293,  36.05556488,  28.66994858]
b= tf.constant(a)
indices =tf.where(b>30)
with tf.Session() as sess :
  sess.run(tf.gather(b, indices))


(2, 3)


In [33]:

###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

a=tf.range(1,7)
tf.diag(a)
with tf.Session() as sess :
  print(sess.run(tf.diag(a)))
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

b=tf.random_normal([10,10])
c=tf.matrix_determinant(b)
with tf.Session() as sess :
  print(sess.run(c))
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################
a= [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9]
x=tf.constant(a)
u=tf.unique(x)
with tf.Session() as sess :
  print(sess.run(u))
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

x= tf.random_normal(shape=[300])
y= tf.random_normal(shape=[300])
aa =tf.reduce_mean(x-y)
def f1() : return tf.reduce_mean(tf.square(x-y))
def f2() : return tf.reduce_sum(tf.abs(x - y))
f= tf.cond(aa <0,f1 , f2)

with tf.Session() as sess:
  print(sess.run(f))


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
-0.92624366
Unique(y=array([ 5,  2,  3, 10,  6,  4,  1,  0,  9], dtype=int32), idx=array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8], dtype=int32))
1.6924267
