[View in Colaboratory](https://colab.research.google.com/github/sungreong/TIL/blob/master/(0805)numpy_76~90.ipynb)

In [8]:
## 76 consider a one-dimensional array Z ,  build a two-dimesonal array
## whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 
## (last row should be (Z[-3],Z[-2],Z[-1]) 
import numpy as np
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print("size = ", np.arange(10).size)
print("shape=" , (np.arange(10).size-3 +1 , 3 ))
print("strides = " , ( np.arange(10).itemsize , np.arange(10).itemsize ) )
print( np.arange(10))
print(Z.shape)
print(Z)

size =  10
shape= (8, 3)
strides =  (8, 8)
[0 1 2 3 4 5 6 7 8 9]
(8, 3)
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [14]:
## 77 HOW TO negative a boolean , or to change the sign of a float inplace
Z = np.random.randint(0, 2 , 100)
print(Z[0:10] , "\n 0 ,1 바꾸기 ")
np.logical_not(Z , out= Z)
print(Z[0:10])
Z = np.random.uniform(-1.0  , 1.0 , 100)
print(Z[0:10] , " \n  부호 바꾸기 ")
np.negative(Z ,out =Z)[0:10]

[0 0 0 0 0 1 0 0 1 1] 
 0 ,1 바꾸기 
[1 1 1 1 1 0 1 1 0 0]
[-0.78680416  0.55293101 -0.05272295  0.64779132  0.59735683 -0.2548658
  0.17721895  0.89952008 -0.31654216  0.16920254]  
  부호 바꾸기 


array([ 0.78680416, -0.55293101,  0.05272295, -0.64779132, -0.59735683,
        0.2548658 , -0.17721895, -0.89952008,  0.31654216, -0.16920254])

In [37]:
## 78 consider 2 sets of points P0 ,P1 describing lines (2d) and  a point p ,
## how to compute distance from p to each line i  (P0[I] , P1[i])?
## 잘 모르겠음 
def distance(P0 , P1 , p ) :
    T = P1-P0
    L = (T**2).sum(axis=1)
    U = -( (P0[:,0] - p[...,0])*T[:,0] + (P0[:, 1] - p[...,1])*T[:,1] ) /L
    U = U.reshape(len(U), 1)
    D= P0 + U*T -p
    return np.sqrt( (D**2).sum(axis=1 ) )

P0 = np.random.uniform(-10 , 10, (10, 2))
P1 = np.random.uniform(-10 ,10 , (10, 2))
p = np.random.uniform(-10, 10, (1,2))
T= P1-P0
L = (T**2).sum(axis=1)
U = -( (P0[:,0] - p[...,0])*T[:,0] + (P0[:, 1] - p[...,1])*T[:,1] ) /L
print("before U.shape", U.shape , "len(U)" , len(U))
U = U.reshape(len(U), 1)
print("after U.shape", U.shape )
D= P0 + U*T -p
print("T = P1 -P0  두 좌표 사이의 차이  \n" , P1 -P0 )
print("L = 차이 제곱의 열을 합침 \n " , ( (P1 -P0 )**2).sum(axis=1))
print(" P0 기준으로 두개 값을 빼고 차이를 곱하고  더한다음 부호를 마이ㄴ \n" , -( (P0[:,0] - p[...,0])*T[:,0] + (P0[:, 1] - p[...,1])*T[:,1] ) )
print("distnact, \n " , distance(P0, P1 , p ))

before U.shape (10,) len(U) 10
after U.shape (10, 1)
T = P1 -P0  두 좌표 사이의 차이  
 [[ -6.31553802  -3.09433316]
 [  6.68378575  -8.43118082]
 [  3.04042493  11.14468256]
 [ -7.87918415   9.23162829]
 [ -9.80116184   4.52645624]
 [  1.46238049  -4.13230569]
 [ -6.27030117  -0.80879123]
 [-11.78994556   2.93590711]
 [ 12.30711365 -10.60880654]
 [  3.25882352  11.54267316]]
L = 차이 제곱의 열을 합침 
  [ 49.46091819 115.75780192 133.44813307 147.30450386 116.55157944
  19.21450702  39.97082004 147.62236697 264.0118225  143.85323439]
 P0 기준으로 두개 값을 빼고 차이를 곱하고  더한다음 부호를 마이ㄴ 
 [-30.86817548  11.33674417  85.3954832  117.10550679  62.85064971
  -6.08254456   4.49397683  28.45629809 101.37795749 195.50709815]
distnact, 
  [ 5.03824458  0.04447048  2.62864833 12.11104774 14.77196163  8.74699567
  3.62864086  1.44063871  3.27527509  3.16603866]


In [52]:
## 80. consider an arbitrary array , write a function that extract a subpart with a fixed shape 
## and centered on a given element (pad with a fill value when necessary )

Z = np.random.randint(0 ,10 , (10, 10))
shape =(5,5)
fill = 0  ; position=(1,1)

R = np.ones(shape , dtype = Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array( list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
print(Rs, Zs)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2) ; print(Rs , Rs//2 , Rs%2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist() ; print(R_start)
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist() ; 

r= [slice(start, stop) for start ,stop in zip(R_start , R_stop)]
z= [slice(start, stop) for start ,stop in zip(Z_start , Z_stop)]
print(r) ; print(z ,"\n")
print(Z)
print(R ,"\n ")
R[r] = Z[z]
print(Z)
print(R)

[5 5] [10 10]
[5 5] [2 2] [1 1]
[1, 1]
[slice(1, 5, None), slice(1, 5, None)]
[slice(0, 4, None), slice(0, 4, None)] 

[[4 5 1 4 8 7 9 8 4 2]
 [9 2 7 6 2 4 1 6 1 3]
 [3 1 5 5 5 2 3 1 3 4]
 [7 5 2 2 6 7 0 6 8 6]
 [4 0 5 3 4 6 6 7 0 7]
 [7 7 3 0 9 7 1 8 3 9]
 [4 9 1 8 4 0 3 0 6 7]
 [1 3 5 1 3 1 4 1 2 4]
 [0 9 1 8 6 0 2 2 1 4]
 [5 3 2 0 3 3 8 2 3 8]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 
 
[[4 5 1 4 8 7 9 8 4 2]
 [9 2 7 6 2 4 1 6 1 3]
 [3 1 5 5 5 2 3 1 3 4]
 [7 5 2 2 6 7 0 6 8 6]
 [4 0 5 3 4 6 6 7 0 7]
 [7 7 3 0 9 7 1 8 3 9]
 [4 9 1 8 4 0 3 0 6 7]
 [1 3 5 1 3 1 4 1 2 4]
 [0 9 1 8 6 0 2 2 1 4]
 [5 3 2 0 3 3 8 2 3 8]]
[[0 0 0 0 0]
 [0 4 5 1 4]
 [0 9 2 7 6]
 [0 3 1 5 5]
 [0 7 5 2 2]]


In [58]:
## 81  consider an array Z = [1,2,3,4,5,6,7,8,9,10, 11,12,13,14] , how to generate an array 
## R = [[1,2,3,4,], [2,3,4,5,], ..[11,12,13,14]]

z = np.arange(1, 15, dtype= np.uint32)
r = stride_tricks.as_strided(z ,shape = (11,4), strides = (4 , 4 ))
r

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

In [64]:
## 82 compute a matrix rank 
z = np.random.uniform(0 , 1, (7, 10))
u ,s ,v= np.linalg.svd(z)
print(u.shape, s.shape, v.shape)
rank= np.sum(s > 1e-10)
print(rank)

(7, 7) (7,) (10, 10)
7


In [69]:
## 83 how to find the most frequent value in an array?
z = np.random.randint(0  ,10 ,  50)
print(np.bincount(z).argmax())
print(np.bincount(z))

0
[10  9  5  3  5  2  4  6  1  5]


In [77]:
## 84 extract all the contiguous 3x3 blocks from a random 10x10 matrix 

z= np.random.randint(0 ,5 , (10, 10))
n = 3
print(z.shape)
i = 1+(z.shape[0] -3)
j = 1+(z.shape[1]-3)
print(z)
print(i  , j )
print(z.strides + z.strides)
c = stride_tricks.as_strided(z , shape=(i , j , n , n ) , strides = z.strides+ z.strides)
print(c.shape)

(10, 10)
[[4 0 3 1 2 4 3 4 4 0]
 [1 1 0 1 3 4 1 3 2 1]
 [3 3 0 2 1 4 2 1 3 0]
 [0 4 4 3 0 3 4 3 1 2]
 [3 0 4 2 2 4 4 4 3 4]
 [4 0 3 4 4 2 0 0 4 1]
 [2 3 2 1 0 4 4 3 1 1]
 [4 2 4 1 2 2 3 2 2 1]
 [3 1 1 1 0 0 3 2 3 1]
 [4 0 4 3 0 1 2 0 2 4]]
8 8
(80, 8, 80, 8)
(8, 8, 3, 3)


In [82]:
## 85 create a 2d array subclass such that Z[i, j ] == Z[j,i]

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(4,4)))
print(S, "\n ")
S[2,3] = 42
print(S)

[[ 6 10  9  8]
 [10  9  4  8]
 [ 9  4  7 15]
 [ 8  8 15  6]] 
 
[[ 6 10  9  8]
 [10  9  4  8]
 [ 9  4  7 42]
 [ 8  8 42  6]]


In [87]:
## 86  consider a set of p matrices which shape ( n, n ) and 
## a set of p vectors with shape (n , 1) .
## how to compute the sum of  the p matrix products at once 
p , n = 10 ,20
M = np.ones((p, n , n))
V = np.ones( (p, n , 1))
S =np.tensordot(M ,V , axes = [[ 0, 2], [0, 1]])
print(S.shape , "\n " ,S[10:20, ])

(20, 1) 
  [[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [96]:
## 87 consider a 16x16 array , how to get the block-sum (block size is 4 x 4 )?

z = np.ones( (16,16 ))
k =4
print(z.shape)
print("\n" , np.arange(0 , z.shape[0], k ))
print('\n' ,  np.add.reduceat( z , np.arange(0 , z.shape[0] , 8  ) ,axis=0 ))
s = np.add.reduceat( np.add.reduceat(z , np.arange(0 , z.shape[0], k) , axis=0 ) , 
                   np.arange(0, z.shape[1] , k ), axis=1 )


print(s)

(16, 16)

 [ 0  4  8 12]

 [[8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [102]:
## 88 how to implement the game of life using numpy arrays
def iterate(z) :
    N = ( z[0:-2 ,  0:-2] + z[0:-2 , 1:-1] + z[0:-2 , 2:] + 
        z[1:-1 , 0:-2] + z[1:-1 , 2:] + 
        z[2: , 0:-2] + z[2: , 1:-1]  + z[2:, 2:])
    
    birth = (N==3) & (z[1:-1, 1:-1]==0) 
    survive = ((N==2) | (N==3)) & (z[1:-1 , 1:-1] == 1)
    z[...] =0
    z[1:-1 , 1:-1][birth | survive] = 1
    return z

z = np.random.randint(0 , 2 ,(50, 50))
print(z[0:-2 , 0:-2].shape)
print(z[0:-2 , 1:-1].shape)
print(z[0:-2 , 2: ].shape)
for i in range(100): Z = iterate(z)
print(Z)

(48, 48)
(48, 48)
(48, 48)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [107]:
## 89 how to get the n largest values of an array
z= np.arange(10000)
np.random.shuffle(z)
n = 5
print(z[np.argsort(z)[-n: ]])
print(z[np.argpartition(-z ,n)])
print(z[np.argpartition(-z ,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 ... 1546 1762 2122]
[9999 9998 9997 9996 9995]


In [132]:
## 90 given an arbitrary number of vectors  build the cartesian product 
## (every combinations of every item )

def cartesian(arrays) :
    arrays = [np.asarray(a) for a in arrays ]
    shape = (len(x) for x in arrays )
    ix = np.indices(shape, dtype= int)
    ix = ix.reshape(len(arrays), -1 ).T
    
    for n ,arr in enumerate(arrays) :
        ix[: , n ] = arrays[n][ix[: ,n ] ]
        
    return ix


arrays =([1,2,3], [4,5], [6,7])
arrays = [np.asarray(a) for a in arrays ]  ; print(arrays)
shape = (len(x) for x in arrays)  ; print(shape) 
ix = np.indices( shape , dtype= int)  ; print(  ix)
print("\n" , arrays[2] , "\n" )
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
<generator object <genexpr> at 0x7fea8f4dfd00>
[[[[0 0]
   [0 0]]

  [[1 1]
   [1 1]]

  [[2 2]
   [2 2]]]


 [[[0 0]
   [1 1]]

  [[0 0]
   [1 1]]

  [[0 0]
   [1 1]]]


 [[[0 1]
   [0 1]]

  [[0 1]
   [0 1]]

  [[0 1]
   [0 1]]]]

 [6 7] 

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [126]:
np.indices((3,3,3))

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]],


       [[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]]],


       [[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]]])