[View in Colaboratory](https://colab.research.google.com/github/sungreong/TIL/blob/master/numpy_re_0721(33%EB%B2%88%EA%B9%8C%EC%A7%80_%ED%95%A8).ipynb)

# REMIND 

https://github.com/sungreong/numpy-100/blob/master/100%20Numpy%20exercises.ipynb


In [0]:
import numpy as np

In [6]:
print(np.__version__)


1.14.5


In [8]:
z= np.zeros(10) ; print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
z = np.zeros((10, 10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [14]:
z = np.zeros(10)
z[4] = 1 
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
z = np.arange(10,50) ; print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
z= np.arange(50) ; z = z[::-1] ; print(z)
print(z[::10])
print(z[::-10])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
[49 39 29 19  9]
[ 0 10 20 30 40]


In [25]:
z = np.arange(9).reshape(3,3) ; print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
z = np.nonzero([1,2,0,0,4,9]) ; print("0이 아닌 인덱스를 뽑아라", z)

0이 아닌 인덱스를 뽑아라 (array([0, 1, 4, 5]),)


In [29]:
z = np.eye(3) ; print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
z= np.random.random((3,3,3)) ; print(z)

[[[0.25015016 0.62092707 0.02289238]
  [0.44474229 0.93432844 0.98637549]
  [0.09360366 0.30612062 0.30539858]]

 [[0.43130133 0.92847849 0.87057345]
  [0.43158331 0.17093279 0.16842536]
  [0.57418676 0.23346049 0.05674516]]

 [[0.92896413 0.59943054 0.08179984]
  [0.77785715 0.00202699 0.7474899 ]
  [0.33264012 0.29345347 0.7289561 ]]]


In [34]:
z = np.random.randn(3,3,3) ; 
zmin , zmax = z.min() , z.max()
print(zmin ,zmax)

-1.939209177715225 1.8765346189542902


In [36]:
z = np.random.randn(30) ; m=z.mean() ; print(m)

0.2780293972446099


In [43]:
z = np.ones((10, 10) )
z[1:-1 , 1:-1] = 0 ; print(z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [50]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=10)
print(Z)
np.shape(Z)

[[10. 10. 10. 10. 10. 10. 10.]
 [10.  1.  1.  1.  1.  1. 10.]
 [10.  1.  1.  1.  1.  1. 10.]
 [10.  1.  1.  1.  1.  1. 10.]
 [10.  1.  1.  1.  1.  1. 10.]
 [10.  1.  1.  1.  1.  1. 10.]
 [10. 10. 10. 10. 10. 10. 10.]]


(7, 7)

In [53]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 0.1*3)  # 0.3 == 0.30000000000000004

nan
False
False
nan
False


In [69]:
z = np.diag(1+ np.arange(5)  ) ; print(z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [70]:
z = np.zeros( (8,8) , dtype="int") 
z[1::2 , ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [79]:
print(np.unravel_index( 25 , (10,10,10 )))

(0, 2, 5)


In [82]:
z = np.tile(np.array([[0,1] , [1,0] ]) , (3, 2 ) )
print(z)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [83]:
## 22
z= np.random.randn(5,5)
zmax ,zmin = z.max(), z.min()
z = (z-zmin) / (zmax - zmin )
print(z)

[[0.32249047 0.35274884 0.64658691 0.21173221 0.39937061]
 [0.88866399 0.41620769 0.         0.23700044 0.06366783]
 [0.94722432 0.30547375 0.52586019 0.21202882 0.36512038]
 [1.         0.96541135 0.46320394 0.2001029  0.00987201]
 [0.32199455 0.24509125 0.7050088  0.54349386 0.61137971]]


In [86]:
color = np.dtype( [ ("r", np.ubyte , 1) , 
                  ("g" , np.ubyte , 1) ,
                  ("b", np.ubyte , 1) , 
                  ("a", np.ubyte , 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [88]:
z = np.dot(np.ones((5,3)) , np.ones( (3,2) )) ; print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [90]:
z = np.arange(11)
z[ (3 < z ) & (z <= 8)] *= -1 
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [103]:
print( sum( range(5) , -1 ) )


9


In [113]:
z / 1 /1 
z/ -1 /-1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

In [115]:
print(np.array(0) / np.array(0) )
print(np.array(0) // np.array(0) )
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [119]:
z = np.random.uniform(-10 , 10 , 10)
print(np.abs(z))
print(np.ceil(np.abs(z)))
print(np.copysign(np.ceil( np.abs(z)) , z ))

[4.22705266 4.44916342 6.60173173 6.83310684 3.24358268 6.11558627
 2.87818016 8.68527076 0.07744458 6.94174339]
[5. 5. 7. 7. 4. 7. 3. 9. 1. 7.]
[-5.  5. -7.  7. -4. -7.  3. -9.  1. -7.]


In [120]:
z1 = np.random.randint(0 ,10 , 10)  ; print(z1)
z2 = np.random.randint(0, 10 , 10) ; print(z2)
print(np.intersect1d(z1, z2 ))

[2 0 5 7 2 5 2 7 9 2]
[0 8 5 6 8 2 1 9 1 6]
[0 2 5 9]


In [125]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(divide="ignore") :
    z = np.ones(1) / 0
    print(z)

[inf]


In [127]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [131]:
## 33 
yesterday = np.datetime64("today", "D" ) - np.timedelta64(1, "D") ; print(yesterday)
today = np.datetime64("today" , "D") ; print(today)
tomorrow = np.datetime64("today" ,"D") + np.timedelta64(10,"D") ; print(tomorrow)

2018-07-20
2018-07-21
2018-07-31
