[View in Colaboratory](https://colab.research.google.com/github/sungreong/TIL/blob/master/(0819)91~100_numpy.ipynb)

In [2]:
## 91 
# how to create a record array from a regular array ? 
import numpy as np

z = np.array([("HELLO" , 2.5 , 3) , 
             ("WORLD" , 3, 2)])

r = np.core.records.fromarrays(z.T , names='name, value1 , value2' , 
                              formats = 'S8 , f8, i8')

print(r)


[(b'HELLO', 2.5, 3) (b'WORLD', 3. , 2)]


In [9]:
## 92
## consider a large vector z , compute z to the power of 3 using 3 different methods 

x = np.random.rand(5000000)

%timeit np.power(x, 3)
%timeit x*x*x
%timeit np.einsum("i,i,i->i" , x,x,x)

1 loop, best of 3: 412 ms per loop
10 loops, best of 3: 51.4 ms per loop
10 loops, best of 3: 38.2 ms per loop


In [33]:
## 93 
# Consider two arrays A and B of shape (8,3) and (2,2). 
# How to find rows of A that contain elements of each row of B 
# regardless of the order of the elements in B

a = np.random.randint(0, 5 , (8,3))
b = np.random.randint(0,5 , (2,2))
# print(np.shape(a[..., np.newaxis, np.newaxis]) )
print(a)
print(b)
# print(a[..., np.newaxis, np.newaxis] ) ## 더 잘게쪼개지는 역할을 하한다 
c = (a[..., np.newaxis, np.newaxis] ==b)  ## 더 잘게 쪼개진것에서 2x2 행렬중에 있는 값이 있으면 TRUE 
print(a[..., np.newaxis, np.newaxis][1:3,1:3,:,:])
print(c[1:3,1:3,:,:] )
print(np.shape(c))
print(c.any((3,1)))
print("\n" ,c.any((3,1)).all(1))
print( np.where(c.any((3,1)).all(1)) )
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[[1 4 0]
 [4 3 2]
 [4 1 0]
 [1 0 1]
 [4 2 2]
 [1 4 3]
 [4 3 1]
 [4 2 0]]
[[0 3]
 [0 0]]
[[[[3]]

  [[2]]]


 [[[1]]

  [[0]]]]
[[[[False  True]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[ True False]
   [ True  True]]]]
(8, 3, 2, 2)
[[ True  True]
 [ True False]
 [ True  True]
 [ True  True]
 [False False]
 [ True False]
 [ True False]
 [ True  True]]

 [ True False  True  True False False False  True]
(array([0, 2, 3, 7]),)
[0 2 3 7]


In [47]:
# 94
## considering a 10x3 matrix , extract rows with unequal values

z= np.random.randint(0 ,5 , (10, 3 ))
print(z[:,1:] ,"\n")
print(z[:,:-1])
e = np.all(z[:,1:] == z[:,:-1] ,axis = 1)
print(e, "\n" , ~e)
u=z[~e]
print(  u)
u = z[z.max(axis=1) != z.min(axis=1) , : ]
print("\n" , u)

[[0 4]
 [3 3]
 [0 2]
 [0 1]
 [0 3]
 [3 4]
 [0 0]
 [1 4]
 [0 1]
 [3 4]] 

[[4 0]
 [1 3]
 [0 0]
 [2 0]
 [3 0]
 [3 3]
 [0 0]
 [0 1]
 [1 0]
 [2 3]]
[False False False False False False  True False False False] 
 [ True  True  True  True  True  True False  True  True  True]
[[4 0 4]
 [1 3 3]
 [0 0 2]
 [2 0 1]
 [3 0 3]
 [3 3 4]
 [0 1 4]
 [1 0 1]
 [2 3 4]]

 [[4 0 4]
 [1 3 3]
 [0 0 2]
 [2 0 1]
 [3 0 3]
 [3 3 4]
 [0 1 4]
 [1 0 1]
 [2 3 4]]


In [64]:
# 95 
## ## convert a vector of ints into a matrix binary representation
l = np.array([ 0, 1, 2,3, 15 , 16, 32 , 128])
print(l.reshape(-1, 1 ) & (2** np.arange(8)) )
b = ( (l.reshape(-1, 1 ) & (2** np.arange(8)) != 0 ).astype(int))
print(b[:,::-1]) ##  convert

l = np.array([0,1,2,3,15,16,32,64,128] , dtype = np.uint8 )
print( np.unpackbits( l[:, np.newaxis ] ,axis=1 ))

[[  0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   0   0]
 [  1   2   0   0   0   0   0   0]
 [  1   2   4   8   0   0   0   0]
 [  0   0   0   0  16   0   0   0]
 [  0   0   0   0   0  32   0   0]
 [  0   0   0   0   0   0   0 128]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [55]:
# 96
## given a two dimensional array , how to extract unique rows
z = np.random.randint(0, 2, (6,3))
t = np.ascontiguousarray(z).view(np.dtype( (np.void, z.dtype.itemsize * z. shape[1]) ) ) 
_, idx = np.unique(t , return_index =True)
print(z)
print(idx , "\n")

uZ = z[idx]
print(uZ)

[[0 0 1]
 [1 1 0]
 [1 0 0]
 [1 1 0]
 [0 0 1]
 [1 0 1]]
[0 2 5 1] 

[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


In [66]:
# 97
## Considering 2 vectors A & B, 
## write the einsum equivalent of inner, outer, sum, and mul function (★★★)

a= np.random.uniform(0, 1, 10)
b= np.random.uniform(0, 1, 10)

np.einsum("i->", a) # np.sum
np.einsum("i,i->i"  , a,b) # a*b
np.einsum("i,i" , a,b) # np.inner
np.einsum("i,j->ij" , a,b) #np.outer


array([[0.74556823, 0.61002983, 0.0810656 , 0.40591352, 0.2981027 ,
        0.19233443, 0.16374584, 0.04315265, 0.18904415, 0.2967106 ],
       [0.52164902, 0.42681736, 0.05671888, 0.28400404, 0.20857243,
        0.13456993, 0.11456746, 0.03019246, 0.13226784, 0.20759843],
       [0.84863404, 0.6943591 , 0.09227195, 0.46202617, 0.3393118 ,
        0.21892234, 0.18638173, 0.04911798, 0.21517723, 0.33772726],
       [0.21006416, 0.17187616, 0.02284027, 0.1143663 , 0.08399056,
        0.0541903 , 0.04613546, 0.01215828, 0.05326327, 0.08359833],
       [0.14378878, 0.11764912, 0.01563415, 0.07828366, 0.05749148,
        0.03709323, 0.03157969, 0.00832233, 0.03645867, 0.057223  ],
       [0.31524949, 0.25793963, 0.03427706, 0.17163289, 0.12604711,
        0.08132499, 0.06923685, 0.01824628, 0.07993376, 0.12545849],
       [0.628576  , 0.51430586, 0.06834504, 0.34221884, 0.25132536,
        0.16215391, 0.13805136, 0.03638127, 0.15937993, 0.2501517 ],
       [0.47662218, 0.38997605, 0.0518231

In [77]:
# 98
# Considering a path described by two vectors (X,Y), 
# how to sample it using equidistant samples (★★★)?

phi = np.arange(0, 10*np.pi , 0.1)
a =1 
x = a*phi*np.cos(phi)
y= a*phi*np.sin(phi)

dr = (np.diff(x)**2  + np.diff(y)**2)**.5
r = np.zeros_like(x)
print(np.shape(r) == np.shape(x))
r[1:] = np.cumsum(dr)
print(r)
r_int = np.linspace(0, r.max() , 200)
x_int = np.interp( r_int , r, x)
print(x_int)
y_int = np.interp( r_int ,r , y )

True
[0.00000000e+00 1.00000000e-01 2.00994225e-01 3.03948099e-01
 4.09773428e-01 5.19310334e-01 6.33316917e-01 7.52465988e-01
 8.77347271e-01 1.00847317e+00 1.14628646e+00 1.29116861e+00
 1.44344797e+00 1.60340735e+00 1.77129076e+00 1.94730924e+00
 2.13164591e+00 2.32446017e+00 2.52589132e+00 2.73606151e+00
 2.95507828e+00 3.18303664e+00 3.42002084e+00 3.66610588e+00
 3.92135873e+00 4.18583938e+00 4.45960178e+00 4.74269456e+00
 5.03516168e+00 5.33704304e+00 5.64837490e+00 5.96919031e+00
 6.29951948e+00 6.63939009e+00 6.98882753e+00 7.34785520e+00
 7.71649464e+00 8.09476576e+00 8.48268698e+00 8.88027538e+00
 9.28754684e+00 9.70451612e+00 1.01311970e+01 1.05676022e+01
 1.10137439e+01 1.14696332e+01 1.19352807e+01 1.24106962e+01
 1.28958890e+01 1.33908678e+01 1.38956409e+01 1.44102161e+01
 1.49346005e+01 1.54688013e+01 1.60128248e+01 1.65666773e+01
 1.71303646e+01 1.77038924e+01 1.82872658e+01 1.88804900e+01
 1.94835697e+01 2.00965094e+01 2.07193135e+01 2.13519861e+01
 2.19945311e+01 2.2

In [88]:
# 99 
# Given an integer n and a 2D array X, 
# select from X the rows which can be interpreted as draws 
# from a multinomial distribution with n degrees, 
#i.e., the rows which only contain integers and which sum to n.
x = np.asarray([[1.0, 0.0, 3.0, 8.0 ] ,
               [2.0, 0.0, 1.0, 1.0] ,
               [1.5 , 2.5, 1.0 ,0.0]])
n =4
m = np.logical_and.reduce(np.mod(x, 1) ==0 , axis =1)
print(np.mod( 1.5 , 1 ))
print(m)  
print(x.sum(axis=-1) )
m &= (x.sum(axis=-1) == n )
print(x[m])

0.5
[ True  True False]
[12.  4.  5.]
[[2. 0. 1. 1.]]


In [91]:
# 100
# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X 
# (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).


x  = np.random.randn(100)
n = 1000 
idx = np.random.randint( 0 ,x.size , (n, x.size)) 
means = x[idx].mean(axis=1)
print( np.shape( means) )
confint = np.percentile( means, [2.5 , 97.5 ])
print(confint)










(1000,)
[-0.17370059  0.15564197]
