[View in Colaboratory](https://colab.research.google.com/github/sungreong/TIL/blob/master/numpy_re_(34~66)_0722.ipynb)

https://github.com/sungreong/numpy-100/blob/master/100%20Numpy%20exercises.ipynb

In [0]:
import numpy as np


In [6]:
z = np.arange("2016-07-06", "2016-09" , dtype= "datetime64[M]") ; print(z)
z = np.arange("2016-07", "2016-08" , dtype= "datetime64[D]") ; print(z)

['2016-07' '2016-08']
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [8]:
a = np.ones(3) * 1
b = np.ones(3) * 2
c = np.ones(3) * 3
np.add(a,b, out= b)
np.divide(a , 2 ,  out = a)
np.negative(a, out = a )
np.multiply(a,b, out = a)

array([-1.5, -1.5, -1.5])

In [11]:
z= np.random.uniform(0, 10, 10)
print(z)
print(z % 1 )
print(z -z %1)  # 
print(np.floor(z)) # 버림
print(np.ceil(z) -1 ) #올림
print(z.astype(int))
print(np.trunc(z))

[0.49056886 8.72219578 2.4943571  1.58888967 7.65332412 3.93440576
 6.2233729  4.0480877  9.66091388 7.26561565]
[0.49056886 0.72219578 0.4943571  0.58888967 0.65332412 0.93440576
 0.2233729  0.0480877  0.66091388 0.26561565]
[0. 8. 2. 1. 7. 3. 6. 4. 9. 7.]
[0. 8. 2. 1. 7. 3. 6. 4. 9. 7.]
[0. 8. 2. 1. 7. 3. 6. 4. 9. 7.]
[0 8 2 1 7 3 6 4 9 7]
[0. 8. 2. 1. 7. 3. 6. 4. 9. 7.]


In [16]:
z = np.zeros( (5,5))
print(np.arange(5)+1)
z += np.arange(5)+1
print(z)

[1 2 3 4 5]
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [21]:
def generate() : 
    for x in range(10) :
        yield x
        

z= np.fromiter(generate() , dtype= float , count = -1 )
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [25]:
z = np.linspace(0, 1, 10, endpoint=False)[1:]
print(len(z))
print(z)
z = np.linspace(0, 1, 10, endpoint=True)[1:]
print(len(z))
print(z)

9
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
9
[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889 1.        ]


In [26]:
z= np.random.random(10)
z.sort()
print(z)

[0.06732237 0.11420995 0.27034006 0.36405174 0.53436073 0.65314827
 0.73057824 0.73887462 0.85804025 0.92102931]


In [30]:
z = np.arange(10)
print( np.sum(z) )
print(np.add.reduce(z) )

45
45


In [31]:
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)

equal = np.allclose(a,b)
print(equal)

equal = np.array_equal(a,b)
print(equal)

False
False


In [37]:
z= np.zeros(10)
z.flags.writeable= False
print(z)
z[0]=1


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: ignored

In [38]:
z = np.random.random( ( 10 ,2 ) ) 
x, y = z[: ,0] , z[: , 1]
r= np.sqrt(x**2 + y**2)
t = np.arctan2(y,x)
print(r) ; print(t)

[0.83011177 0.79758799 0.92032537 1.30674715 1.03205106 0.93648813
 0.65912715 0.54609043 1.00251136 0.96533514]
[0.84578348 1.1038597  0.37246456 0.80981099 0.49024628 0.42991514
 0.46855096 0.72837814 1.48503274 0.03042592]


In [40]:
z= np.random.random(10)
print(z.argmax())
z[z.argmax()] = 0
print(z)

1
[0.7450398  0.         0.80961017 0.21481072 0.5079989  0.45128934
 0.36473039 0.68919575 0.25234901 0.73372271]


In [42]:
z = np.zeros( ( 5, 5 ) , [("x", float) , ("y", float)])
print(z)
z["x"] , z["y"] = np.meshgrid(np.linspace( 0, 1,5) , np.linspace(0 , 1, 5))
print(z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [45]:
x = np.arange(8)
y =  x + 0.5 
print(np.subtract.outer(x,y ))
print(np.shape(np.subtract.outer(x,y )))
c = 1.0 / np.subtract.outer(x, y) 
print(np.linalg.det(c))

[[-0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5 -7.5]
 [ 0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5 -6.5]
 [ 1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5 -5.5]
 [ 2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5 -4.5]
 [ 3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5 -3.5]
 [ 4.5  3.5  2.5  1.5  0.5 -0.5 -1.5 -2.5]
 [ 5.5  4.5  3.5  2.5  1.5  0.5 -0.5 -1.5]
 [ 6.5  5.5  4.5  3.5  2.5  1.5  0.5 -0.5]]
(8, 8)
3638.163637117973


In [48]:
np.set_printoptions(threshold=np.nan)
z= np.zeros(( 16, 16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [49]:
z = np.arange(100)
v = np.random.uniform(0, 100)
index = ((np.abs(z-v)).argmin())
print(index , z[index])

93 93


In [51]:
z = np.zeros(10 , [ ("position" , [ ("x" , float) , ("y", float)]) ,
                            ("color" , [ ("r" , float , 1 ) , 
                                            ("g" , float , 1) ,
                                            ("b", float , 1  )])])

print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [56]:
z= np.random.random( ( 10 , 2 ))
x, y = np.atleast_2d(z[:, 0] , z[:, 1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

import scipy
import scipy.spatial
print("="*100)
z= np.random.random( ( 10, 2 ))
d= scipy.spatial.distance.cdist(z,z)
print(d)

[[0.         0.91954616 0.34065892 0.8879132  0.16267062 0.13564186
  0.86907416 0.25849748 0.51593029 0.61322695]
 [0.91954616 0.         0.8384588  0.41203524 1.0221768  0.86482435
  0.22825235 0.67174811 0.70403836 0.35714695]
 [0.34065892 0.8384588  0.         0.96150982 0.29416928 0.20540023
  0.87621894 0.2708477  0.72905804 0.64588   ]
 [0.8879132  0.41203524 0.96150982 0.         1.03386569 0.89483234
  0.18423079 0.71088742 0.46115349 0.31650873]
 [0.16267062 1.0221768  0.29416928 1.03386569 0.         0.15758078
  0.99852097 0.35173777 0.67809136 0.74420325]
 [0.13564186 0.86482435 0.20540023 0.89483234 0.15758078 0.
  0.84792691 0.19618029 0.5801184  0.59591611]
 [0.86907416 0.22825235 0.87621894 0.18423079 0.99852097 0.84792691
  0.         0.65328303 0.53735842 0.25586826]
 [0.25849748 0.67174811 0.2708477  0.71088742 0.35173777 0.19618029
  0.65328303 0.         0.46295207 0.40403421]
 [0.51593029 0.70403836 0.72905804 0.46115349 0.67809136 0.5801184
  0.53735842 0.462952

In [58]:
z= np.arange(10, dtype= np.float32) 
print(z)
z= z.astype(np.int32 , copy =False)
print(z)
0

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


In [60]:
z= np.arange(9).reshape(3,3) 
for index ,value in np.ndenumerate(z) :
    print(index , value) ;

for index in np.ndindex(z.shape) :
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [66]:
x, y = np.meshgrid( np.linspace(-1 , 1, 10) , np.linspace(-1 , 1 , 10)) 
print(np.shape(x)) ; print(np.shape(y))
d= np.sqrt(x*x+y*y)

sigma , mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / (2.0*sigma**2 )))
print(g)

(10, 10)
(10, 10)
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444

In [68]:
n = 10 
p =3 
z= np.zeros( ( n, n))
print(np.random.choice( range(n*n) , p , replace= False))
np.put(z, np.random.choice( range(n*n) , p , replace= False) , 1 )
print(z)

[24 16 17]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [73]:
x= np.random.rand(5, 10)
d = x.mean(axis=1  ,  keepdims=True)
print(np.shape(d))
y = x - x.mean(axis=1  ,  keepdims=True)
print(y)

(5, 1)
[[0.42261421]
 [0.56821618]
 [0.33549065]
 [0.59154217]
 [0.42955991]]
[[ 0.10326636 -0.24285499  0.022474   -0.39346364 -0.16396142  0.32636138
   0.13703116 -0.03160567  0.10303264  0.1397202 ]
 [-0.04422726  0.03964843 -0.37286671 -0.47688715  0.01295303  0.38004908
  -0.03873096  0.28764444  0.34885521 -0.13643811]
 [ 0.47547125  0.08164749  0.02476461  0.27756808 -0.1855128  -0.28347994
  -0.20981396 -0.2693139   0.3078191  -0.21914993]
 [ 0.06516226 -0.07048697  0.22114143 -0.15107547  0.08165365 -0.35744428
   0.02667448  0.28643086  0.21329306 -0.31534903]
 [ 0.44108531  0.43796625  0.35197144  0.15489017 -0.11873359 -0.40318535
  -0.26588368 -0.25673675 -0.36269344  0.02131964]]


In [75]:
z= np.random.randint( 0 , 10 , (3,3))
print(z) 
## 특정열 정렬시키기
print(z[z[:,1].argsort()] )

[[0 3 5]
 [5 2 0]
 [2 9 9]]
[[5 2 0]
 [0 3 5]
 [2 9 9]]


In [80]:
z= np.random.randint(0 ,3, (3,10 ))
print(z)
print( z.any(axis=0) )
print((~z.any(axis=0)).any())

[[0 1 1 0 2 2 0 2 1 2]
 [1 0 2 1 2 0 0 1 0 1]
 [2 1 1 1 0 2 0 0 2 1]]
[ True  True  True  True  True  True False  True  True  True]
True


In [83]:
z= np.random.uniform(0, 1, 10)
a= 0.6
m = z.flat[np.abs(z-a).argmin()]
print(m)
m = z[np.abs(z-a).argmin()]
print(m)

0.6259335375936687
0.6259335375936687


In [89]:
a  = np.arange(3).reshape(3,1) ; print(a)
b= np.arange(3).reshape(1, 3)  ; print(b)
it = np.nditer([a,b , None]) ; print(it)
for x, y, z in it : 
    z[...] = x+y
print([it.operands[2]])



[[0]
 [1]
 [2]]
[[0 1 2]]
[array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])]


In [93]:
z= np.ones(10)
l = np.random.randint(0 , len(z) , 20)
print(l)
# 나오는 숫자를 카운트하는 것 -= bincount
print(np.bincount(l , minlength =len(z)))
z += np.bincount(l , minlength =len(z))
print(z)

np.add.at(z,l,1)
print(z)

[7 2 1 4 1 5 9 3 8 1 0 7 5 0 1 1 7 9 2 1]
[2 6 2 1 1 2 0 3 1 2]
[3. 7. 3. 2. 2. 3. 1. 4. 2. 3.]
[ 5. 13.  5.  3.  3.  5.  1.  7.  3.  5.]


In [100]:
## 65 번까지 

x= [1,2,3,4,5,6]
y = [1,3,9,3,4,1]
f = np.bincount(y, x)
print(f)
##  y 가 1 부터 9 숫자 사이에 있으므로  0 부터 9 까지의 인덱스가 생성된다.
## 그 중 1에 인덱스가 매칭이 되는 x는 1, 6 
## 2 는 없고, 3은 2와 4  / 4는 5 / 5는 없고 /6도 없고/ 7도 없고/8도없고/9는 3 
## 결과겂은 이것들의 합을 하면 빈도가 나온다.

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [0]:
,